import MobileModule from "./module/MobileModule.js";
import AosModule from "./module/AosModule.js";
import BtnToTopModule from "./module/BtnToTopModule.js";
import PopupModule from "./module/PopupModule.js";
import SwiperModule from "./module/SwiperModule.js";
import CountUpModule from "./module/CountUpModule.js";
import SearchModule from "./module/SearchModule.js";
import Select2Module from "./module/Select2Module.js";
import GalleryModule from "./module/GalleryModule.js";
import TabModule from "./module/TabModule.js";
import HeaderModule from "./module/HeaderModule.js";
import SideModule from "./module/SideModule.js";
import CollapseModule from "./module/CollapseModule.js";
import AnimatedModule from "./module/AnimatedModule.js";
import TextAniModule from "./module/TextAniModule.js";
import ScrollTriggerModule from "./module/ScrollTriggerModule.js";
import ComponentModule from "./module/ComponentModule.js";
import ButtonModule from "./module/ButtonModule.js";
import HoverParallax from "./module/HoverParallax.js";
import CountDownModule from "./module/CountDownModule.js";
import ConfettiModule from "./module/ConfettiModule.js";
import ProductFilter from "./module/ProductFilter.js";

window.addEventListener("DOMContentLoaded", () => {
    TextAniModule();
    AnimatedModule();
    ScrollTriggerModule();
    AosModule();
    TabModule();
    Select2Module();
    CountUpModule();
    SwiperModule();
    MobileModule();
    BtnToTopModule();
    HeaderModule();
    PopupModule();
    GalleryModule();
    SearchModule();
    SideModule();
    CollapseModule();
    ComponentModule();
    ButtonModule();
    HoverParallax();
    CountDownModule();
    ConfettiModule();
    ProductFilter();
});